// Single source of truth for the site-wide "which country am I browsing/
// listing in" concept (Listing.country) — mirrors soukmar/src/app/models/
// country.model.ts and soukmar-backend/src/lib/countries.ts EXACTLY (same
// COUNTRIES array, same CITIES_BY_COUNTRY curated set), via the same
// generation script already used for soukmar-android's CountryModels.kt —
// no hand-transcription across ~193 countries. If the web list changes,
// re-run the extraction rather than editing this file by hand.
//
// Codes are ISO 3166-1 alpha-2, same as web/Android, so this stays
// interchangeable with the backend's Listing.country column. Country
// *names* are never hand-translated here — Locale(identifier:).localizedString(forRegionCode:)
// is the Swift equivalent of Intl.DisplayNames (CLDR-backed), used at call
// sites instead of a hardcoded name table.

import Foundation

enum ContinentRegion: String, CaseIterable, Hashable {
    case morocco = "MOROCCO"
    case africa = "AFRICA"
    case europe = "EUROPE"
    case asia = "ASIA"
    case northAmerica = "NORTH_AMERICA"
    case southAmerica = "SOUTH_AMERICA"
    case oceania = "OCEANIA"
}

struct CountryInfo {
    let code: String
    let region: ContinentRegion
    let currency: String
}

let COUNTRIES: [CountryInfo] = [
    CountryInfo(code: "MA", region: .morocco, currency: "MAD"),
    CountryInfo(code: "DZ", region: .africa, currency: "DZD"),
    CountryInfo(code: "TN", region: .africa, currency: "TND"),
    CountryInfo(code: "LY", region: .africa, currency: "LYD"),
    CountryInfo(code: "EG", region: .africa, currency: "EGP"),
    CountryInfo(code: "SD", region: .africa, currency: "SDG"),
    CountryInfo(code: "SS", region: .africa, currency: "SSP"),
    CountryInfo(code: "MR", region: .africa, currency: "MRU"),
    CountryInfo(code: "ML", region: .africa, currency: "XOF"),
    CountryInfo(code: "NE", region: .africa, currency: "XOF"),
    CountryInfo(code: "TD", region: .africa, currency: "XAF"),
    CountryInfo(code: "SN", region: .africa, currency: "XOF"),
    CountryInfo(code: "GM", region: .africa, currency: "GMD"),
    CountryInfo(code: "GW", region: .africa, currency: "XOF"),
    CountryInfo(code: "GN", region: .africa, currency: "GNF"),
    CountryInfo(code: "SL", region: .africa, currency: "SLE"),
    CountryInfo(code: "LR", region: .africa, currency: "LRD"),
    CountryInfo(code: "CI", region: .africa, currency: "XOF"),
    CountryInfo(code: "GH", region: .africa, currency: "GHS"),
    CountryInfo(code: "TG", region: .africa, currency: "XOF"),
    CountryInfo(code: "BJ", region: .africa, currency: "XOF"),
    CountryInfo(code: "NG", region: .africa, currency: "NGN"),
    CountryInfo(code: "CM", region: .africa, currency: "XAF"),
    CountryInfo(code: "CF", region: .africa, currency: "XAF"),
    CountryInfo(code: "GQ", region: .africa, currency: "XAF"),
    CountryInfo(code: "GA", region: .africa, currency: "XAF"),
    CountryInfo(code: "CG", region: .africa, currency: "XAF"),
    CountryInfo(code: "CD", region: .africa, currency: "CDF"),
    CountryInfo(code: "AO", region: .africa, currency: "AOA"),
    CountryInfo(code: "ZM", region: .africa, currency: "ZMW"),
    CountryInfo(code: "MW", region: .africa, currency: "MWK"),
    CountryInfo(code: "MZ", region: .africa, currency: "MZN"),
    CountryInfo(code: "ZW", region: .africa, currency: "ZWL"),
    CountryInfo(code: "BW", region: .africa, currency: "BWP"),
    CountryInfo(code: "NA", region: .africa, currency: "NAD"),
    CountryInfo(code: "ZA", region: .africa, currency: "ZAR"),
    CountryInfo(code: "LS", region: .africa, currency: "LSL"),
    CountryInfo(code: "SZ", region: .africa, currency: "SZL"),
    CountryInfo(code: "KE", region: .africa, currency: "KES"),
    CountryInfo(code: "TZ", region: .africa, currency: "TZS"),
    CountryInfo(code: "UG", region: .africa, currency: "UGX"),
    CountryInfo(code: "RW", region: .africa, currency: "RWF"),
    CountryInfo(code: "BI", region: .africa, currency: "BIF"),
    CountryInfo(code: "ET", region: .africa, currency: "ETB"),
    CountryInfo(code: "ER", region: .africa, currency: "ERN"),
    CountryInfo(code: "DJ", region: .africa, currency: "DJF"),
    CountryInfo(code: "SO", region: .africa, currency: "SOS"),
    CountryInfo(code: "BF", region: .africa, currency: "XOF"),
    CountryInfo(code: "CV", region: .africa, currency: "CVE"),
    CountryInfo(code: "ST", region: .africa, currency: "STN"),
    CountryInfo(code: "SC", region: .africa, currency: "SCR"),
    CountryInfo(code: "MU", region: .africa, currency: "MUR"),
    CountryInfo(code: "MG", region: .africa, currency: "MGA"),
    CountryInfo(code: "KM", region: .africa, currency: "KMF"),
    CountryInfo(code: "FR", region: .europe, currency: "EUR"),
    CountryInfo(code: "ES", region: .europe, currency: "EUR"),
    CountryInfo(code: "DE", region: .europe, currency: "EUR"),
    CountryInfo(code: "IT", region: .europe, currency: "EUR"),
    CountryInfo(code: "PT", region: .europe, currency: "EUR"),
    CountryInfo(code: "NL", region: .europe, currency: "EUR"),
    CountryInfo(code: "BE", region: .europe, currency: "EUR"),
    CountryInfo(code: "LU", region: .europe, currency: "EUR"),
    CountryInfo(code: "GB", region: .europe, currency: "GBP"),
    CountryInfo(code: "IE", region: .europe, currency: "EUR"),
    CountryInfo(code: "CH", region: .europe, currency: "CHF"),
    CountryInfo(code: "AT", region: .europe, currency: "EUR"),
    CountryInfo(code: "SE", region: .europe, currency: "SEK"),
    CountryInfo(code: "NO", region: .europe, currency: "NOK"),
    CountryInfo(code: "DK", region: .europe, currency: "DKK"),
    CountryInfo(code: "FI", region: .europe, currency: "EUR"),
    CountryInfo(code: "IS", region: .europe, currency: "ISK"),
    CountryInfo(code: "PL", region: .europe, currency: "PLN"),
    CountryInfo(code: "CZ", region: .europe, currency: "CZK"),
    CountryInfo(code: "SK", region: .europe, currency: "EUR"),
    CountryInfo(code: "HU", region: .europe, currency: "HUF"),
    CountryInfo(code: "RO", region: .europe, currency: "RON"),
    CountryInfo(code: "BG", region: .europe, currency: "BGN"),
    CountryInfo(code: "GR", region: .europe, currency: "EUR"),
    CountryInfo(code: "HR", region: .europe, currency: "EUR"),
    CountryInfo(code: "SI", region: .europe, currency: "EUR"),
    CountryInfo(code: "RS", region: .europe, currency: "RSD"),
    CountryInfo(code: "BA", region: .europe, currency: "BAM"),
    CountryInfo(code: "ME", region: .europe, currency: "EUR"),
    CountryInfo(code: "MK", region: .europe, currency: "MKD"),
    CountryInfo(code: "AL", region: .europe, currency: "ALL"),
    CountryInfo(code: "XK", region: .europe, currency: "EUR"),
    CountryInfo(code: "LT", region: .europe, currency: "EUR"),
    CountryInfo(code: "LV", region: .europe, currency: "EUR"),
    CountryInfo(code: "EE", region: .europe, currency: "EUR"),
    CountryInfo(code: "MD", region: .europe, currency: "MDL"),
    CountryInfo(code: "UA", region: .europe, currency: "UAH"),
    CountryInfo(code: "BY", region: .europe, currency: "BYN"),
    CountryInfo(code: "RU", region: .europe, currency: "RUB"),
    CountryInfo(code: "MT", region: .europe, currency: "EUR"),
    CountryInfo(code: "CY", region: .europe, currency: "EUR"),
    CountryInfo(code: "AD", region: .europe, currency: "EUR"),
    CountryInfo(code: "MC", region: .europe, currency: "EUR"),
    CountryInfo(code: "LI", region: .europe, currency: "CHF"),
    CountryInfo(code: "SM", region: .europe, currency: "EUR"),
    CountryInfo(code: "VA", region: .europe, currency: "EUR"),
    CountryInfo(code: "TR", region: .asia, currency: "TRY"),
    CountryInfo(code: "IL", region: .asia, currency: "ILS"),
    CountryInfo(code: "PS", region: .asia, currency: "ILS"),
    CountryInfo(code: "JO", region: .asia, currency: "JOD"),
    CountryInfo(code: "LB", region: .asia, currency: "LBP"),
    CountryInfo(code: "SY", region: .asia, currency: "SYP"),
    CountryInfo(code: "IQ", region: .asia, currency: "IQD"),
    CountryInfo(code: "SA", region: .asia, currency: "SAR"),
    CountryInfo(code: "YE", region: .asia, currency: "YER"),
    CountryInfo(code: "OM", region: .asia, currency: "OMR"),
    CountryInfo(code: "AE", region: .asia, currency: "AED"),
    CountryInfo(code: "QA", region: .asia, currency: "QAR"),
    CountryInfo(code: "BH", region: .asia, currency: "BHD"),
    CountryInfo(code: "KW", region: .asia, currency: "KWD"),
    CountryInfo(code: "IR", region: .asia, currency: "IRR"),
    CountryInfo(code: "AF", region: .asia, currency: "AFN"),
    CountryInfo(code: "PK", region: .asia, currency: "PKR"),
    CountryInfo(code: "IN", region: .asia, currency: "INR"),
    CountryInfo(code: "BD", region: .asia, currency: "BDT"),
    CountryInfo(code: "LK", region: .asia, currency: "LKR"),
    CountryInfo(code: "NP", region: .asia, currency: "NPR"),
    CountryInfo(code: "BT", region: .asia, currency: "BTN"),
    CountryInfo(code: "MM", region: .asia, currency: "MMK"),
    CountryInfo(code: "TH", region: .asia, currency: "THB"),
    CountryInfo(code: "LA", region: .asia, currency: "LAK"),
    CountryInfo(code: "KH", region: .asia, currency: "KHR"),
    CountryInfo(code: "VN", region: .asia, currency: "VND"),
    CountryInfo(code: "MY", region: .asia, currency: "MYR"),
    CountryInfo(code: "SG", region: .asia, currency: "SGD"),
    CountryInfo(code: "ID", region: .asia, currency: "IDR"),
    CountryInfo(code: "PH", region: .asia, currency: "PHP"),
    CountryInfo(code: "BN", region: .asia, currency: "BND"),
    CountryInfo(code: "TL", region: .asia, currency: "USD"),
    CountryInfo(code: "CN", region: .asia, currency: "CNY"),
    CountryInfo(code: "JP", region: .asia, currency: "JPY"),
    CountryInfo(code: "KR", region: .asia, currency: "KRW"),
    CountryInfo(code: "KP", region: .asia, currency: "KPW"),
    CountryInfo(code: "MN", region: .asia, currency: "MNT"),
    CountryInfo(code: "TW", region: .asia, currency: "TWD"),
    CountryInfo(code: "HK", region: .asia, currency: "HKD"),
    CountryInfo(code: "MO", region: .asia, currency: "MOP"),
    CountryInfo(code: "KZ", region: .asia, currency: "KZT"),
    CountryInfo(code: "UZ", region: .asia, currency: "UZS"),
    CountryInfo(code: "TM", region: .asia, currency: "TMT"),
    CountryInfo(code: "TJ", region: .asia, currency: "TJS"),
    CountryInfo(code: "KG", region: .asia, currency: "KGS"),
    CountryInfo(code: "AM", region: .asia, currency: "AMD"),
    CountryInfo(code: "AZ", region: .asia, currency: "AZN"),
    CountryInfo(code: "GE", region: .asia, currency: "GEL"),
    CountryInfo(code: "MV", region: .asia, currency: "MVR"),
    CountryInfo(code: "US", region: .northAmerica, currency: "USD"),
    CountryInfo(code: "CA", region: .northAmerica, currency: "CAD"),
    CountryInfo(code: "MX", region: .northAmerica, currency: "MXN"),
    CountryInfo(code: "GT", region: .northAmerica, currency: "GTQ"),
    CountryInfo(code: "BZ", region: .northAmerica, currency: "BZD"),
    CountryInfo(code: "SV", region: .northAmerica, currency: "USD"),
    CountryInfo(code: "HN", region: .northAmerica, currency: "HNL"),
    CountryInfo(code: "NI", region: .northAmerica, currency: "NIO"),
    CountryInfo(code: "CR", region: .northAmerica, currency: "CRC"),
    CountryInfo(code: "PA", region: .northAmerica, currency: "PAB"),
    CountryInfo(code: "CU", region: .northAmerica, currency: "CUP"),
    CountryInfo(code: "JM", region: .northAmerica, currency: "JMD"),
    CountryInfo(code: "HT", region: .northAmerica, currency: "HTG"),
    CountryInfo(code: "DO", region: .northAmerica, currency: "DOP"),
    CountryInfo(code: "BS", region: .northAmerica, currency: "BSD"),
    CountryInfo(code: "BB", region: .northAmerica, currency: "BBD"),
    CountryInfo(code: "TT", region: .northAmerica, currency: "TTD"),
    CountryInfo(code: "GD", region: .northAmerica, currency: "XCD"),
    CountryInfo(code: "LC", region: .northAmerica, currency: "XCD"),
    CountryInfo(code: "VC", region: .northAmerica, currency: "XCD"),
    CountryInfo(code: "AG", region: .northAmerica, currency: "XCD"),
    CountryInfo(code: "DM", region: .northAmerica, currency: "XCD"),
    CountryInfo(code: "KN", region: .northAmerica, currency: "XCD"),
    CountryInfo(code: "BR", region: .southAmerica, currency: "BRL"),
    CountryInfo(code: "AR", region: .southAmerica, currency: "ARS"),
    CountryInfo(code: "CL", region: .southAmerica, currency: "CLP"),
    CountryInfo(code: "CO", region: .southAmerica, currency: "COP"),
    CountryInfo(code: "PE", region: .southAmerica, currency: "PEN"),
    CountryInfo(code: "VE", region: .southAmerica, currency: "VES"),
    CountryInfo(code: "EC", region: .southAmerica, currency: "USD"),
    CountryInfo(code: "BO", region: .southAmerica, currency: "BOB"),
    CountryInfo(code: "PY", region: .southAmerica, currency: "PYG"),
    CountryInfo(code: "UY", region: .southAmerica, currency: "UYU"),
    CountryInfo(code: "GY", region: .southAmerica, currency: "GYD"),
    CountryInfo(code: "SR", region: .southAmerica, currency: "SRD"),
    CountryInfo(code: "AU", region: .oceania, currency: "AUD"),
    CountryInfo(code: "NZ", region: .oceania, currency: "NZD"),
    CountryInfo(code: "FJ", region: .oceania, currency: "FJD"),
    CountryInfo(code: "PG", region: .oceania, currency: "PGK"),
    CountryInfo(code: "SB", region: .oceania, currency: "SBD"),
    CountryInfo(code: "VU", region: .oceania, currency: "VUV"),
    CountryInfo(code: "WS", region: .oceania, currency: "WST"),
    CountryInfo(code: "TO", region: .oceania, currency: "TOP"),
]

private let COUNTRY_BY_CODE: [String: CountryInfo] = Dictionary(uniqueKeysWithValues: COUNTRIES.map { ($0.code, $0) })

func currencyForCountry(_ code: String) -> String {
    COUNTRY_BY_CODE[code]?.currency ?? "USD"
}

func isKnownCountry(_ code: String) -> Bool {
    COUNTRY_BY_CODE[code] != nil
}

/// i18n key for a continent group's label in a country picker, e.g.
/// "deposer.region_europe" — shared by the country picker so the mapping
/// lives in exactly one place.
func regionLabelKey(_ region: ContinentRegion) -> String {
    "deposer.region_" + region.rawValue.lowercased()
}

/// One continent group's countries, for a picker's Section list — a plain
/// struct rather than a tuple so SwiftUI's `ForEach(id:)` has an unambiguous
/// `Hashable` keypath to use (no local compiler here to double-check a tuple
/// keypath actually resolves the way it's expected to).
struct CountryRegionGroup: Hashable {
    let region: ContinentRegion
    let codes: [String]
}

/// Groups the full country list into continents for pickers — Morocco
/// pinned first as the platform's home market, then continents in a fixed,
/// stable order (mirrors web's COUNTRY_REGIONS / Android's COUNTRY_REGIONS).
let COUNTRY_REGIONS: [CountryRegionGroup] = {
    let order: [ContinentRegion] = [.morocco, .africa, .europe, .asia, .northAmerica, .southAmerica, .oceania]
    return order.map { region in CountryRegionGroup(region: region, codes: COUNTRIES.filter { $0.region == region }.map { $0.code }) }
}()

/// Major/mid-size cities for the ~30 countries curated in an earlier round
/// (ported 1:1 from web's CITIES_BY_COUNTRY / Android's CountryModels.kt).
/// Every other country in COUNTRIES has no entry here on purpose — the city
/// field falls back to free text for those, exactly like web/Android.
let CITIES_BY_COUNTRY: [String: [String]] = [
    "FR": ["Paris", "Marseille", "Lyon", "Toulouse", "Nice", "Nantes", "Strasbourg", "Montpellier", "Bordeaux", "Lille", "Rennes", "Reims", "Le Havre", "Saint-Étienne", "Toulon", "Grenoble", "Dijon", "Angers", "Nîmes", "Villeurbanne", "Clermont-Ferrand", "Le Mans", "Aix-en-Provence", "Brest", "Tours", "Limoges", "Amiens", "Annecy", "Perpignan", "Besançon", "Metz", "Orléans", "Rouen", "Mulhouse", "Caen", "Nancy", "Argenteuil", "Saint-Denis", "Roubaix", "Tourcoing", "Avignon", "Créteil", "Poitiers", "Versailles", "Pau", "La Rochelle", "Calais", "Cannes", "Antibes", "Béziers"],
    "ES": ["Madrid", "Barcelona", "Valencia", "Sevilla", "Zaragoza", "Malaga", "Murcia", "Palma", "Las Palmas", "Bilbao", "Alicante", "Córdoba", "Valladolid", "Vigo", "Gijón", "Vitoria-Gasteiz", "A Coruña", "Granada", "Elche", "Oviedo", "Badalona", "Cartagena", "Terrassa", "Jerez de la Frontera", "Sabadell", "Móstoles", "Alcalá de Henares", "Pamplona", "Fuenlabrada", "Almería", "San Sebastián", "Leganés", "Santander", "Burgos", "Castellón de la Plana", "Getafe", "Albacete", "Alcorcón", "Logroño", "Badajoz", "Salamanca", "Huelva", "Marbella", "Tarragona", "León", "Cádiz", "Lleida", "Dos Hermanas", "Mataró", "Santa Cruz de Tenerife"],
    "DE": ["Berlin", "Hamburg", "Munich", "Cologne", "Frankfurt", "Stuttgart", "Düsseldorf", "Leipzig", "Dortmund", "Essen", "Bremen", "Dresden", "Hannover", "Nuremberg", "Duisburg", "Bochum", "Wuppertal", "Bielefeld", "Bonn", "Münster", "Mannheim", "Karlsruhe", "Augsburg", "Wiesbaden", "Mönchengladbach", "Gelsenkirchen", "Braunschweig", "Chemnitz", "Kiel", "Aachen", "Halle", "Magdeburg", "Freiburg", "Krefeld", "Lübeck", "Oberhausen", "Erfurt", "Mainz", "Rostock", "Kassel", "Hagen", "Saarbrücken", "Hamm", "Potsdam", "Ludwigshafen", "Oldenburg", "Leverkusen", "Osnabrück", "Solingen", "Heidelberg"],
    "IT": ["Rome", "Milan", "Naples", "Turin", "Palermo", "Genoa", "Bologna", "Florence", "Bari", "Catania", "Venice", "Verona", "Messina", "Padua", "Trieste", "Taranto", "Brescia", "Parma", "Prato", "Modena", "Reggio Calabria", "Reggio Emilia", "Perugia", "Ravenna", "Livorno", "Cagliari", "Foggia", "Rimini", "Salerno", "Ferrara", "Sassari", "Latina", "Monza", "Syracuse", "Pescara", "Bergamo", "Trento", "Forlì", "Vicenza", "Terni", "Bolzano", "Novara", "Piacenza", "Ancona", "Andria", "Arezzo", "Udine", "Cesena", "Lecce", "La Spezia"],
    "PT": ["Lisbon", "Porto", "Vila Nova de Gaia", "Amadora", "Braga", "Funchal", "Coimbra", "Setúbal", "Almada", "Agualva-Cacém", "Queluz", "Barreiro", "Aveiro", "Faro", "Évora", "Viseu", "Guimarães", "Leiria", "Portimão", "Odivelas", "Barcelos", "Póvoa de Varzim", "Rio Maior", "Viana do Castelo", "Vila Real", "Covilhã", "Tomar", "Torres Vedras", "Peniche", "Elvas", "Beja", "Chaves", "Estoril", "Cascais", "Sintra", "Loures", "Matosinhos"],
    "NL": ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven", "Tilburg", "Groningen", "Almere", "Breda", "Nijmegen", "Enschede", "Haarlem", "Arnhem", "Zaanstad", "Amersfoort", "Apeldoorn", "Hoofddorp", "Maastricht", "Leiden", "Dordrecht", "Zoetermeer", "Zwolle", "Deventer", "Delft", "Alkmaar", "Heerlen", "Venlo", "Leeuwarden", "Hilversum", "Amstelveen", "Purmerend", "Roosendaal", "Oss", "Schiedam", "Spijkenisse", "Vlaardingen", "Almelo", "Gouda", "Hengelo", "Emmen"],
    "BE": ["Brussels", "Antwerp", "Ghent", "Charleroi", "Liège", "Bruges", "Namur", "Leuven", "Mons", "Aalst", "Mechelen", "La Louvière", "Kortrijk", "Hasselt", "Sint-Niklaas", "Ostend", "Tournai", "Genk", "Seraing", "Roeselare", "Verviers", "Mouscron", "Beveren", "Dendermonde", "Beringen", "Turnhout", "Dilbeek", "Heist-op-den-Berg", "Lokeren", "Vilvoorde"],
    "GB": ["London", "Birmingham", "Manchester", "Glasgow", "Liverpool", "Leeds", "Sheffield", "Edinburgh", "Bristol", "Cardiff", "Leicester", "Belfast", "Nottingham", "Newcastle upon Tyne", "Southampton", "Portsmouth", "Bradford", "Coventry", "Kingston upon Hull", "Stoke-on-Trent", "Wolverhampton", "Plymouth", "Derby", "Swansea", "Aberdeen", "Reading", "Milton Keynes", "Northampton", "Norwich", "Luton", "York", "Oxford", "Cambridge", "Preston", "Sunderland", "Middlesbrough", "Blackpool", "Bolton", "Ipswich", "Watford", "Slough", "Exeter", "Gloucester", "Dundee", "Blackburn", "Southend-on-Sea", "Peterborough", "Bath", "Brighton", "Warrington"],
    "CH": ["Zurich", "Geneva", "Basel", "Lausanne", "Bern", "Winterthur", "Lucerne", "St. Gallen", "Lugano", "Biel/Bienne", "Thun", "Köniz", "La Chaux-de-Fonds", "Fribourg", "Schaffhausen", "Chur", "Vernier", "Neuchâtel", "Uster", "Sion", "Emmen", "Zug", "Yverdon-les-Bains", "Kriens", "Rapperswil-Jona", "Dübendorf", "Montreux", "Dietikon", "Frauenfeld", "Wetzikon"],
    "AT": ["Vienna", "Graz", "Linz", "Salzburg", "Innsbruck", "Klagenfurt", "Villach", "Wels", "Sankt Pölten", "Dornbirn", "Wiener Neustadt", "Steyr", "Feldkirch", "Bregenz", "Leonding", "Klosterneuburg", "Baden", "Wolfsberg", "Leoben", "Krems an der Donau", "Traun", "Amstetten", "Lustenau", "Kapfenberg", "Hallein"],
    "SE": ["Stockholm", "Gothenburg", "Malmö", "Uppsala", "Västerås", "Örebro", "Linköping", "Helsingborg", "Jönköping", "Norrköping", "Lund", "Umeå", "Gävle", "Borås", "Södertälje", "Eskilstuna", "Halmstad", "Växjö", "Karlstad", "Sundsvall", "Trollhättan", "Östersund", "Borlänge", "Falun", "Kalmar"],
    "PL": ["Warsaw", "Kraków", "Łódź", "Wrocław", "Poznań", "Gdańsk", "Szczecin", "Bydgoszcz", "Lublin", "Białystok", "Katowice", "Gdynia", "Częstochowa", "Radom", "Sosnowiec", "Toruń", "Kielce", "Gliwice", "Zabrze", "Bytom", "Olsztyn", "Bielsko-Biała", "Rzeszów", "Ruda Śląska", "Rybnik", "Tychy", "Opole", "Gorzów Wielkopolski", "Płock", "Wałbrzych", "Włocławek", "Elbląg", "Zielona Góra", "Koszalin"],
    "GR": ["Athens", "Thessaloniki", "Patras", "Heraklion", "Larissa", "Volos", "Rhodes", "Ioannina", "Chania", "Chalcis", "Agrinio", "Katerini", "Trikala", "Serres", "Lamia", "Alexandroupoli", "Xanthi", "Kavala", "Kalamata", "Kozani", "Veroia", "Drama", "Komotini", "Rethymno", "Karditsa"],
    "IE": ["Dublin", "Cork", "Limerick", "Galway", "Waterford", "Drogheda", "Dundalk", "Swords", "Bray", "Navan", "Kilkenny", "Ennis", "Carlow", "Tralee", "Naas", "Sligo", "Athlone", "Wexford", "Letterkenny", "Celbridge"],
    "DK": ["Copenhagen", "Aarhus", "Odense", "Aalborg", "Esbjerg", "Randers", "Kolding", "Horsens", "Vejle", "Roskilde", "Herning", "Silkeborg", "Næstved", "Fredericia", "Viborg", "Køge", "Holstebro", "Taastrup", "Slagelse", "Hillerød"],
    "DZ": ["Algiers", "Oran", "Constantine", "Annaba", "Blida", "Batna", "Djelfa", "Sétif", "Sidi Bel Abbès", "Biskra", "Tébessa", "Tlemcen", "Béjaïa", "Skikda", "Tiaret", "Ouargla", "Bordj Bou Arréridj", "Béchar", "Mostaganem", "Chlef", "Médéa", "El Oued", "Relizane", "Tizi Ouzou", "M'Sila", "Mascara", "Ghardaïa", "Souk Ahras", "Jijel", "Saïda"],
    "TN": ["Tunis", "Sfax", "Sousse", "Kairouan", "Bizerte", "Gabès", "Ariana", "Gafsa", "Monastir", "Ben Arous", "Kasserine", "Médenine", "Nabeul", "Tataouine", "Béja", "Jendouba", "Mahdia", "Sidi Bouzid", "Tozeur", "Zaghouan", "Siliana", "Kef", "Manouba"],
    "LY": ["Tripoli", "Benghazi", "Misrata", "Zawiya", "Bayda", "Zliten", "Ajdabiya", "Tobruk", "Sabha", "Sirte", "Derna", "Khoms"],
    "MR": ["Nouakchott", "Nouadhibou", "Kiffa", "Kaédi", "Rosso", "Zouérat", "Atar", "Néma", "Sélibaby", "Aleg", "Akjoujt"],
    "SN": ["Dakar", "Touba", "Thiès", "Kaolack", "M'bour", "Ziguinchor", "Diourbel", "Saint-Louis", "Louga", "Tambacounda", "Kolda", "Rufisque", "Mbacké", "Richard Toll", "Kaffrine", "Fatick", "Kédougou"],
    "ML": ["Bamako", "Sikasso", "Mopti", "Koutiala", "Ségou", "Kayes", "Gao", "Kati", "San", "Timbuktu", "Kolondiéba", "Bougouni", "Koulikoro"],
    "EG": ["Cairo", "Alexandria", "Giza", "Shubra El Kheima", "Port Said", "Suez", "Luxor", "Mansoura", "El Mahalla El Kubra", "Tanta", "Asyut", "Ismailia", "Faiyum", "Zagazig", "Aswan", "Damietta", "Damanhur", "Minya", "Beni Suef", "Qena", "Sohag", "Hurghada", "6th of October City", "Shibin El Kom", "Banha"],
    "NG": ["Lagos", "Kano", "Ibadan", "Abuja", "Port Harcourt", "Benin City", "Maiduguri", "Zaria", "Aba", "Jos", "Ilorin", "Oyo", "Enugu", "Abeokuta", "Kaduna", "Onitsha", "Warri", "Sokoto", "Calabar", "Katsina", "Akure", "Bauchi", "Owerri", "Uyo", "Ado-Ekiti"],
    "CI": ["Abidjan", "Bouaké", "Daloa", "Yamoussoukro", "Korhogo", "San-Pédro", "Man", "Divo", "Gagnoa", "Anyama", "Abengourou", "Agboville", "Grand-Bassam", "Dabou", "Bondoukou", "Séguéla"],
    "GH": ["Accra", "Kumasi", "Tamale", "Sekondi-Takoradi", "Sunyani", "Cape Coast", "Obuasi", "Teshie", "Tema", "Koforidua", "Ho", "Wa", "Bolgatanga", "Techiman", "Nkawkaw"],
    "CM": ["Douala", "Yaoundé", "Garoua", "Bamenda", "Maroua", "Bafoussam", "Ngaoundéré", "Bertoua", "Loum", "Kumba", "Nkongsamba", "Buea", "Edéa", "Kribi", "Ebolowa"],
    "ZA": ["Johannesburg", "Cape Town", "Durban", "Pretoria", "Port Elizabeth", "Bloemfontein", "Nelspruit", "Kimberley", "Polokwane", "Pietermaritzburg", "Rustenburg", "George", "Welkom", "East London", "Vereeniging", "Klerksdorp", "Potchefstroom", "Vryburg", "Upington", "Worcester"],
    "KE": ["Nairobi", "Mombasa", "Kisumu", "Nakuru", "Eldoret", "Thika", "Malindi", "Kitale", "Garissa", "Kakamega", "Nyeri", "Machakos", "Meru", "Kericho", "Embu"],
    "ET": ["Addis Ababa", "Dire Dawa", "Mekelle", "Gondar", "Adama", "Hawassa", "Bahir Dar", "Jimma", "Jijiga", "Dessie", "Shashamane", "Bishoftu", "Sodo", "Arba Minch", "Hosaena"],
    "TZ": ["Dar es Salaam", "Dodoma", "Mwanza", "Arusha", "Mbeya", "Morogoro", "Tanga", "Kahama", "Tabora", "Zanzibar City", "Kigoma", "Sumbawanga", "Kasulu", "Songea", "Musoma"],
    "SD": ["Khartoum", "Omdurman", "Nyala", "Port Sudan", "Kassala", "El Obeid", "Wad Madani", "El Fasher", "Gedaref", "Kosti", "Atbara", "Dongola", "Sennar", "Nahud", "El Daein"],
    "SS": ["Juba", "Wau", "Malakal", "Yei", "Aweil", "Bor", "Yambio", "Bentiu", "Rumbek", "Torit"],
    "NE": ["Niamey", "Zinder", "Maradi", "Agadez", "Tahoua", "Dosso", "Tillabéri", "Diffa", "Arlit", "Birni-N'Konni"],
    "TD": ["N'Djamena", "Moundou", "Sarh", "Abéché", "Kelo", "Koumra", "Pala", "Am Timan", "Bongor", "Mongo"],
    "GM": ["Banjul", "Serekunda", "Brikama", "Bakau", "Farafenni", "Lamin", "Sukuta", "Basse Santa Su", "Gunjur", "Soma"],
    "GW": ["Bissau", "Bafatá", "Gabú", "Bissorã", "Bolama", "Cacheu", "Catió", "Farim", "Mansôa", "Buba"],
    "GN": ["Conakry", "Nzérékoré", "Kankan", "Kindia", "Labé", "Mamou", "Boké", "Faranah", "Kissidougou", "Siguiri"],
    "SL": ["Freetown", "Bo", "Kenema", "Makeni", "Koidu", "Waterloo", "Lunsar", "Port Loko", "Kabala", "Magburaka"],
    "LR": ["Monrovia", "Gbarnga", "Kakata", "Bensonville", "Harper", "Voinjama", "Buchanan", "Zwedru", "Ganta", "Robertsport"],
    "TG": ["Lomé", "Sokodé", "Kara", "Kpalimé", "Atakpamé", "Dapaong", "Tsévié", "Aného", "Mango", "Bassar"],
    "BJ": ["Cotonou", "Porto-Novo", "Parakou", "Djougou", "Bohicon", "Kandi", "Abomey", "Natitingou", "Lokossa", "Ouidah"],
    "CF": ["Bangui", "Bimbo", "Berbérati", "Carnot", "Bambari", "Bouar", "Bossangoa", "Bria", "Bangassou", "Nola"],
    "GQ": ["Malabo", "Bata", "Ebebiyín", "Aconibe", "Añisoc", "Luba", "Evinayong", "Mongomo", "Mengomeyén", "Micomeseng"],
    "GA": ["Libreville", "Port-Gentil", "Franceville", "Oyem", "Moanda", "Mouila", "Lambaréné", "Tchibanga", "Koulamoutou", "Makokou"],
    "CG": ["Brazzaville", "Pointe-Noire", "Dolisie", "Nkayi", "Ouesso", "Impfondo", "Madingou", "Owando", "Sibiti", "Gamboma"],
    "CD": ["Kinshasa", "Lubumbashi", "Mbuji-Mayi", "Kananga", "Kisangani", "Bukavu", "Goma", "Kolwezi", "Likasi", "Tshikapa", "Uvira", "Matadi", "Mbandaka", "Kikwit", "Bunia"],
    "AO": ["Luanda", "Huambo", "Lobito", "Benguela", "Kuito", "Lubango", "Malanje", "Namibe", "Soyo", "Cabinda", "Uíge", "Saurimo"],
    "ZM": ["Lusaka", "Kitwe", "Ndola", "Kabwe", "Chingola", "Mufulira", "Livingstone", "Luanshya", "Kasama", "Chipata"],
    "MW": ["Lilongwe", "Blantyre", "Mzuzu", "Zomba", "Kasungu", "Mangochi", "Karonga", "Salima", "Nkhotakota", "Balaka"],
    "MZ": ["Maputo", "Matola", "Beira", "Nampula", "Chimoio", "Nacala", "Quelimane", "Tete", "Xai-Xai", "Lichinga", "Pemba"],
    "ZW": ["Harare", "Bulawayo", "Chitungwiza", "Mutare", "Gweru", "Epworth", "Kwekwe", "Kadoma", "Masvingo", "Chinhoyi", "Marondera"],
    "BW": ["Gaborone", "Francistown", "Molepolole", "Selebi-Phikwe", "Maun", "Serowe", "Kanye", "Mahalapye", "Mochudi", "Mogoditshane"],
    "NA": ["Windhoek", "Rundu", "Walvis Bay", "Swakopmund", "Oshakati", "Rehoboth", "Katima Mulilo", "Otjiwarongo", "Okahandja", "Gobabis"],
    "LS": ["Maseru", "Teyateyaneng", "Mafeteng", "Hlotse", "Maputsoe", "Mohale's Hoek", "Quthing", "Qacha's Nek", "Butha-Buthe", "Mokhotlong"],
    "SZ": ["Mbabane", "Manzini", "Big Bend", "Malkerns", "Nhlangano", "Piggs Peak", "Siteki", "Hlatikulu", "Lobamba", "Simunye"],
    "UG": ["Kampala", "Nansana", "Kira", "Ssabagabo", "Mbarara", "Mukono", "Gulu", "Lira", "Mbale", "Jinja", "Kasese", "Masaka"],
    "RW": ["Kigali", "Butare", "Gitarama", "Ruhengeri", "Gisenyi", "Byumba", "Cyangugu", "Kibungo", "Kibuye", "Nyanza"],
    "BI": ["Bujumbura", "Gitega", "Muyinga", "Ruyigi", "Ngozi", "Kayanza", "Rumonge", "Bururi", "Cibitoke", "Muramvya"],
    "ER": ["Asmara", "Keren", "Massawa", "Assab", "Mendefera", "Barentu", "Adi Keyh", "Dekemhare", "Ghinda", "Nakfa"],
    "DJ": ["Djibouti City", "Ali Sabieh", "Tadjourah", "Obock", "Dikhil", "Arta", "Holhol", "Yoboki", "Balho", "Randa"],
    "SO": ["Mogadishu", "Hargeisa", "Bosaso", "Kismayo", "Merca", "Berbera", "Baidoa", "Galkayo", "Jowhar", "Beledweyne"],
    "BF": ["Ouagadougou", "Bobo-Dioulasso", "Koudougou", "Ouahigouya", "Banfora", "Kaya", "Tenkodogo", "Fada N'Gourma", "Dédougou", "Houndé"],
    "CV": ["Praia", "Mindelo", "Santa Maria", "Espargos", "Assomada", "Pedra Badejo", "Tarrafal", "Porto Novo", "São Filipe", "Sal Rei"],
    "ST": ["São Tomé", "Santo António", "Neves", "Santana", "Trindade", "Guadalupe", "Santo Amaro", "São João dos Angolares", "Porto Alegre", "Pantufo"],
    "SC": ["Victoria", "Anse Boileau", "Beau Vallon", "Anse Royale", "Takamaka", "Cascade", "Grand Anse", "Bel Ombre", "Port Glaud", "Baie Lazare"],
    "MU": ["Port Louis", "Beau Bassin-Rose Hill", "Vacoas-Phoenix", "Curepipe", "Quatre Bornes", "Triolet", "Goodlands", "Centre de Flacq", "Bel Air", "Mahébourg"],
    "MG": ["Antananarivo", "Toamasina", "Antsirabe", "Fianarantsoa", "Mahajanga", "Toliara", "Antsiranana", "Ambovombe", "Morondava", "Ambatondrazaka"],
    "KM": ["Moroni", "Mutsamudu", "Fomboni", "Domoni", "Tsimbeo", "Mitsamiouli", "Ouani", "Sima", "Mramani", "Foumbouni"],
    "LU": ["Luxembourg City", "Esch-sur-Alzette", "Differdange", "Dudelange", "Ettelbruck", "Diekirch", "Wiltz", "Echternach", "Rumelange", "Grevenmacher"],
    "NO": ["Oslo", "Bergen", "Trondheim", "Stavanger", "Drammen", "Fredrikstad", "Kristiansand", "Sandnes", "Tromsø", "Sarpsborg", "Skien", "Ålesund", "Bodø", "Sandefjord", "Haugesund"],
    "FI": ["Helsinki", "Espoo", "Tampere", "Vantaa", "Oulu", "Turku", "Jyväskylä", "Lahti", "Kuopio", "Pori", "Kouvola", "Joensuu", "Lappeenranta", "Vaasa", "Rovaniemi"],
    "IS": ["Reykjavík", "Kópavogur", "Hafnarfjörður", "Akureyri", "Reykjanesbær", "Garðabær", "Mosfellsbær", "Árborg", "Akranes", "Fjarðabyggð"],
    "CZ": ["Prague", "Brno", "Ostrava", "Plzeň", "Liberec", "Olomouc", "Ústí nad Labem", "České Budějovice", "Hradec Králové", "Pardubice", "Zlín", "Havířov", "Kladno", "Most"],
    "SK": ["Bratislava", "Košice", "Prešov", "Žilina", "Nitra", "Banská Bystrica", "Trnava", "Martin", "Trenčín", "Poprad"],
    "HU": ["Budapest", "Debrecen", "Szeged", "Miskolc", "Pécs", "Győr", "Nyíregyháza", "Kecskemét", "Székesfehérvár", "Szombathely"],
    "RO": ["Bucharest", "Cluj-Napoca", "Timișoara", "Iași", "Constanța", "Craiova", "Brașov", "Galați", "Ploiești", "Oradea", "Brăila", "Arad", "Sibiu", "Bacău"],
    "BG": ["Sofia", "Plovdiv", "Varna", "Burgas", "Ruse", "Stara Zagora", "Pleven", "Sliven", "Dobrich", "Shumen"],
    "HR": ["Zagreb", "Split", "Rijeka", "Osijek", "Zadar", "Slavonski Brod", "Pula", "Karlovac", "Sisak", "Varaždin"],
    "SI": ["Ljubljana", "Maribor", "Celje", "Kranj", "Velenje", "Koper", "Novo Mesto", "Ptuj", "Trbovlje", "Kamnik"],
    "RS": ["Belgrade", "Novi Sad", "Niš", "Kragujevac", "Subotica", "Zrenjanin", "Pančevo", "Čačak", "Kruševac", "Kraljevo"],
    "BA": ["Sarajevo", "Banja Luka", "Tuzla", "Zenica", "Mostar", "Bijeljina", "Brčko", "Prijedor", "Trebinje", "Doboj"],
    "ME": ["Podgorica", "Nikšić", "Herceg Novi", "Pljevlja", "Bijelo Polje", "Cetinje", "Bar", "Budva", "Kotor", "Berane"],
    "MK": ["Skopje", "Bitola", "Kumanovo", "Prilep", "Tetovo", "Veles", "Štip", "Ohrid", "Gostivar", "Strumica"],
    "AL": ["Tirana", "Durrës", "Vlorë", "Elbasan", "Shkodër", "Fier", "Korçë", "Berat", "Lushnjë", "Kavajë"],
    "XK": ["Pristina", "Prizren", "Ferizaj", "Peja", "Gjakova", "Gjilan", "Mitrovica", "Podujeva", "Vushtrri", "Suhareka"],
    "LT": ["Vilnius", "Kaunas", "Klaipėda", "Šiauliai", "Panevėžys", "Alytus", "Marijampolė", "Mažeikiai", "Jonava", "Utena"],
    "LV": ["Riga", "Daugavpils", "Liepāja", "Jelgava", "Jūrmala", "Ventspils", "Rēzekne", "Valmiera", "Jēkabpils", "Ogre"],
    "EE": ["Tallinn", "Tartu", "Narva", "Pärnu", "Kohtla-Järve", "Viljandi", "Rakvere", "Maardu", "Kuressaare", "Sillamäe"],
    "MD": ["Chișinău", "Tiraspol", "Bălți", "Bender", "Rîbnița", "Cahul", "Ungheni", "Soroca", "Orhei", "Comrat"],
    "UA": ["Kyiv", "Kharkiv", "Odesa", "Dnipro", "Donetsk", "Zaporizhzhia", "Lviv", "Kryvyi Rih", "Mykolaiv", "Mariupol", "Vinnytsia", "Chernihiv"],
    "BY": ["Minsk", "Gomel", "Mogilev", "Vitebsk", "Grodno", "Brest", "Babruysk", "Baranovichi", "Borisov", "Pinsk"],
    "RU": ["Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg", "Kazan", "Nizhny Novgorod", "Chelyabinsk", "Samara", "Omsk", "Rostov-on-Don", "Ufa", "Krasnoyarsk", "Voronezh", "Perm", "Volgograd"],
    "MT": ["Valletta", "Birkirkara", "Mosta", "Qormi", "Żabbar", "San Pawl il-Baħar", "Sliema", "Żejtun", "Fgura", "Rabat"],
    "CY": ["Nicosia", "Limassol", "Larnaca", "Famagusta", "Paphos", "Kyrenia", "Paralimni", "Aradippou", "Strovolos", "Lakatamia"],
    "AD": ["Andorra la Vella", "Escaldes-Engordany", "Encamp", "Sant Julià de Lòria", "La Massana", "Santa Coloma", "Ordino", "Canillo", "Pas de la Casa", "Arinsal"],
    "MC": ["Monaco-Ville", "Monte Carlo", "La Condamine", "Fontvieille", "Moneghetti", "Larvotto", "Saint Roman", "La Rousse", "Les Révoires", "Le Portier"],
    "LI": ["Vaduz", "Schaan", "Triesen", "Balzers", "Eschen", "Mauren", "Triesenberg", "Ruggell", "Gamprin", "Schellenberg"],
    "SM": ["San Marino City", "Serravalle", "Borgo Maggiore", "Domagnano", "Fiorentino", "Acquaviva", "Faetano", "Montegiardino", "Chiesanuova", "San Giovanni"],
    "VA": ["Vatican City"],
    "TR": ["Istanbul", "Ankara", "Izmir", "Bursa", "Antalya", "Adana", "Konya", "Gaziantep", "Şanlıurfa", "Kayseri", "Mersin", "Eskişehir", "Diyarbakır", "Samsun", "Denizli"],
    "IL": ["Jerusalem", "Tel Aviv", "Haifa", "Rishon LeZion", "Petah Tikva", "Ashdod", "Netanya", "Beersheba", "Bnei Brak", "Holon"],
    "PS": ["Gaza", "Ramallah", "Hebron", "Nablus", "Bethlehem", "Khan Yunis", "Jenin", "Rafah", "Tulkarm", "Qalqilya"],
    "JO": ["Amman", "Zarqa", "Irbid", "Russeifa", "Aqaba", "Salt", "Madaba", "Mafraq", "Karak", "Jerash"],
    "LB": ["Beirut", "Tripoli", "Sidon", "Tyre", "Zahlé", "Baalbek", "Byblos", "Jounieh", "Batroun", "Nabatieh"],
    "SY": ["Damascus", "Aleppo", "Homs", "Latakia", "Hama", "Deir ez-Zor", "Raqqa", "Daraa", "Tartus", "Idlib"],
    "IQ": ["Baghdad", "Basra", "Mosul", "Erbil", "Najaf", "Karbala", "Kirkuk", "Sulaymaniyah", "Nasiriyah", "Amara"],
    "SA": ["Riyadh", "Jeddah", "Mecca", "Medina", "Dammam", "Khobar", "Taif", "Tabuk", "Buraidah", "Khamis Mushait", "Hail", "Najran"],
    "YE": ["Sanaa", "Aden", "Taiz", "Hodeidah", "Ibb", "Mukalla", "Dhamar", "Amran", "Sayyan", "Zinjibar"],
    "OM": ["Muscat", "Seeb", "Salalah", "Bawshar", "Sohar", "Sur", "Nizwa", "Ibri", "Rustaq", "Buraimi"],
    "AE": ["Dubai", "Abu Dhabi", "Sharjah", "Al Ain", "Ajman", "Ras Al Khaimah", "Fujairah", "Umm Al Quwain", "Khor Fakkan", "Kalba"],
    "QA": ["Doha", "Al Rayyan", "Al Wakrah", "Al Khor", "Umm Salal", "Al Shamal", "Mesaieed", "Dukhan", "Al Daayen", "Lusail"],
    "BH": ["Manama", "Riffa", "Muharraq", "Hamad Town", "A'ali", "Isa Town", "Sitra", "Budaiya", "Jidhafs", "Al Malikiyah"],
    "KW": ["Kuwait City", "Al Ahmadi", "Hawalli", "As Salimiyah", "Sabah as Salim", "Al Farwaniyah", "Al Jahra", "Al Fintas", "Al Fahahil", "Mangaf"],
    "IR": ["Tehran", "Mashhad", "Isfahan", "Karaj", "Shiraz", "Tabriz", "Qom", "Ahvaz", "Kermanshah", "Urmia", "Rasht", "Zahedan"],
    "AF": ["Kabul", "Kandahar", "Herat", "Mazar-i-Sharif", "Kunduz", "Jalalabad", "Lashkar Gah", "Taloqan", "Puli Khumri", "Ghazni"],
    "PK": ["Karachi", "Lahore", "Faisalabad", "Rawalpindi", "Multan", "Hyderabad", "Gujranwala", "Peshawar", "Islamabad", "Quetta", "Sialkot", "Bahawalpur"],
    "IN": ["Mumbai", "Delhi", "Bengaluru", "Hyderabad", "Ahmedabad", "Chennai", "Kolkata", "Surat", "Pune", "Jaipur", "Lucknow", "Kanpur", "Nagpur", "Indore", "Bhopal", "Patna", "Vadodara", "Ghaziabad"],
    "BD": ["Dhaka", "Chittagong", "Khulna", "Rajshahi", "Sylhet", "Comilla", "Rangpur", "Mymensingh", "Barisal", "Gazipur"],
    "LK": ["Colombo", "Dehiwala-Mount Lavinia", "Kandy", "Galle", "Jaffna", "Negombo", "Trincomalee", "Batticaloa", "Anuradhapura", "Matara"],
    "NP": ["Kathmandu", "Pokhara", "Lalitpur", "Biratnagar", "Bharatpur", "Birgunj", "Dharan", "Butwal", "Hetauda", "Janakpur"],
    "BT": ["Thimphu", "Phuntsholing", "Punakha", "Paro", "Gelephu", "Samdrup Jongkhar", "Wangdue Phodrang", "Trashigang", "Jakar", "Trongsa"],
    "MM": ["Yangon", "Mandalay", "Naypyidaw", "Mawlamyine", "Bago", "Pathein", "Monywa", "Meiktila", "Myitkyina", "Taunggyi"],
    "TH": ["Bangkok", "Nonthaburi", "Nakhon Ratchasima", "Chiang Mai", "Hat Yai", "Udon Thani", "Pak Kret", "Khon Kaen", "Rayong", "Surat Thani"],
    "LA": ["Vientiane", "Pakse", "Savannakhet", "Luang Prabang", "Xam Neua", "Thakhek", "Muang Xay", "Vang Vieng", "Attapeu", "Phonsavan"],
    "KH": ["Phnom Penh", "Siem Reap", "Battambang", "Sihanoukville", "Poipet", "Kampong Cham", "Ta Khmau", "Pursat", "Kampot", "Kratie"],
    "VN": ["Ho Chi Minh City", "Hanoi", "Da Nang", "Hai Phong", "Can Tho", "Bien Hoa", "Hue", "Nha Trang", "Buon Ma Thuot", "Vung Tau"],
    "MY": ["Kuala Lumpur", "George Town", "Ipoh", "Shah Alam", "Petaling Jaya", "Johor Bahru", "Malacca City", "Kota Kinabalu", "Kuching", "Seremban"],
    "SG": ["Singapore", "Jurong West", "Woodlands", "Tampines", "Sengkang", "Hougang", "Yishun", "Bedok", "Punggol", "Ang Mo Kio"],
    "ID": ["Jakarta", "Surabaya", "Bandung", "Medan", "Semarang", "Makassar", "Palembang", "Depok", "Tangerang", "Bekasi", "Bogor", "Batam", "Denpasar", "Yogyakarta"],
    "PH": ["Manila", "Quezon City", "Davao City", "Caloocan", "Cebu City", "Zamboanga City", "Taguig", "Antipolo", "Pasig", "Cagayan de Oro"],
    "BN": ["Bandar Seri Begawan", "Kuala Belait", "Seria", "Tutong", "Bangar", "Muara", "Jerudong", "Lumut", "Sengkurong", "Tanjong Bunut"],
    "TL": ["Dili", "Baucau", "Maliana", "Suai", "Liquiçá", "Aileu", "Ainaro", "Same", "Los Palos", "Viqueque"],
    "CN": ["Shanghai", "Beijing", "Chongqing", "Guangzhou", "Shenzhen", "Chengdu", "Tianjin", "Wuhan", "Xi'an", "Hangzhou", "Nanjing", "Shenyang", "Qingdao", "Dalian", "Zhengzhou", "Harbin", "Kunming", "Xiamen"],
    "JP": ["Tokyo", "Yokohama", "Osaka", "Nagoya", "Sapporo", "Fukuoka", "Kobe", "Kyoto", "Kawasaki", "Saitama", "Hiroshima", "Sendai", "Chiba", "Kitakyushu"],
    "KR": ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon", "Gwangju", "Suwon", "Ulsan", "Changwon", "Goyang"],
    "KP": ["Pyongyang", "Hamhung", "Chongjin", "Nampo", "Wonsan", "Sinuiju", "Tanchon", "Kaesong", "Sariwon", "Hyesan"],
    "MN": ["Ulaanbaatar", "Erdenet", "Darkhan", "Choibalsan", "Mörön", "Nalaikh", "Khovd", "Ölgii", "Baganuur", "Sükhbaatar"],
    "TW": ["Taipei", "Kaohsiung", "Taichung", "Tainan", "Taoyuan", "Hsinchu", "Keelung", "Chiayi", "Changhua", "Yunlin"],
    "HK": ["Hong Kong Island", "Kowloon", "Tsuen Wan", "Sha Tin", "Tuen Mun", "Yuen Long", "Tai Po", "Sai Kung", "North Point", "Kwun Tong"],
    "MO": ["Macau", "Taipa", "Coloane", "Cotai"],
    "KZ": ["Almaty", "Astana", "Shymkent", "Karaganda", "Aktobe", "Taraz", "Pavlodar", "Ust-Kamenogorsk", "Semey", "Atyrau"],
    "UZ": ["Tashkent", "Namangan", "Samarkand", "Andijan", "Nukus", "Bukhara", "Qarshi", "Fergana", "Jizzakh", "Termez"],
    "TM": ["Ashgabat", "Türkmenabat", "Daşoguz", "Mary", "Balkanabat", "Bayramaly", "Tejen", "Serdar", "Abadan", "Baýramaly"],
    "TJ": ["Dushanbe", "Khujand", "Kulob", "Bokhtar", "Istaravshan", "Konibodom", "Tursunzoda", "Panjakent", "Vahdat", "Isfara"],
    "KG": ["Bishkek", "Osh", "Jalal-Abad", "Karakol", "Tokmok", "Kara-Balta", "Naryn", "Talas", "Batken", "Uzgen"],
    "AM": ["Yerevan", "Gyumri", "Vanadzor", "Vagharshapat", "Abovyan", "Kapan", "Hrazdan", "Armavir", "Artashat", "Ijevan"],
    "AZ": ["Baku", "Ganja", "Sumqayit", "Mingachevir", "Lankaran", "Shirvan", "Nakhchivan", "Shaki", "Yevlakh", "Khankendi"],
    "GE": ["Tbilisi", "Batumi", "Kutaisi", "Rustavi", "Zugdidi", "Gori", "Poti", "Samtredia", "Khashuri", "Senaki"],
    "MV": ["Malé", "Addu City", "Fuvahmulah", "Kulhudhuffushi", "Thinadhoo", "Naifaru", "Hithadhoo", "Dhidhdhoo", "Eydhafushi", "Funadhoo"],
    "US": ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio", "San Diego", "Dallas", "San Jose", "Austin", "Jacksonville", "San Francisco", "Columbus", "Charlotte", "Indianapolis", "Seattle", "Denver", "Washington", "Boston", "Miami", "Atlanta", "Las Vegas", "Detroit", "Portland"],
    "CA": ["Toronto", "Montreal", "Vancouver", "Calgary", "Edmonton", "Ottawa", "Winnipeg", "Quebec City", "Hamilton", "Kitchener", "London", "Victoria", "Halifax", "Saskatoon", "Regina"],
    "MX": ["Mexico City", "Guadalajara", "Monterrey", "Puebla", "Tijuana", "León", "Juárez", "Zapopan", "Mérida", "Cancún", "Querétaro", "Chihuahua", "San Luis Potosí", "Acapulco"],
    "GT": ["Guatemala City", "Mixco", "Villa Nueva", "Quetzaltenango", "Escuintla", "Chinautla", "Chimaltenango", "Huehuetenango", "Antigua Guatemala", "Cobán"],
    "BZ": ["Belize City", "San Ignacio", "Orange Walk", "Belmopan", "Dangriga", "Corozal", "San Pedro", "Benque Viejo", "Punta Gorda", "Placencia"],
    "SV": ["San Salvador", "Santa Ana", "San Miguel", "Soyapango", "Mejicanos", "Santa Tecla", "Apopa", "Delgado", "Sonsonate", "Ahuachapán"],
    "HN": ["Tegucigalpa", "San Pedro Sula", "Choloma", "La Ceiba", "El Progreso", "Choluteca", "Comayagua", "Puerto Cortés", "Danlí", "Siguatepeque"],
    "NI": ["Managua", "León", "Masaya", "Chinandega", "Matagalpa", "Granada", "Estelí", "Tipitapa", "Jinotega", "Juigalpa"],
    "CR": ["San José", "Alajuela", "Cartago", "Heredia", "Liberia", "Puntarenas", "Limón", "Desamparados", "San Isidro", "Pérez Zeledón"],
    "PA": ["Panama City", "San Miguelito", "Tocumen", "David", "Arraiján", "Colón", "La Chorrera", "Santiago", "Chitré", "Penonomé"],
    "CU": ["Havana", "Santiago de Cuba", "Camagüey", "Holguín", "Guantánamo", "Santa Clara", "Bayamo", "Cienfuegos", "Pinar del Río", "Matanzas"],
    "JM": ["Kingston", "Spanish Town", "Portmore", "Montego Bay", "May Pen", "Mandeville", "Old Harbour", "Savanna-la-Mar", "Ocho Rios", "Port Antonio"],
    "HT": ["Port-au-Prince", "Cap-Haïtien", "Carrefour", "Delmas", "Pétion-Ville", "Gonaïves", "Croix-des-Bouquets", "Les Cayes", "Jacmel", "Léogâne"],
    "DO": ["Santo Domingo", "Santiago de los Caballeros", "Santo Domingo Este", "La Romana", "San Pedro de Macorís", "San Cristóbal", "Puerto Plata", "La Vega", "Higüey", "Moca"],
    "BS": ["Nassau", "Freeport", "West End", "Coopers Town", "Marsh Harbour", "Freetown", "High Rock", "Andros Town", "George Town", "Alice Town"],
    "BB": ["Bridgetown", "Speightstown", "Oistins", "Bathsheba", "Holetown", "Crane", "Six Roads", "Bayville", "Blackmans", "Checker Hall"],
    "TT": ["Port of Spain", "San Fernando", "Chaguanas", "Arima", "Point Fortin", "Scarborough", "Sangre Grande", "Couva", "Princes Town", "Tunapuna"],
    "GD": ["St. George's", "Gouyave", "Grenville", "Victoria", "Sauteurs", "Hillsborough", "Grand Roy", "Birch Grove", "Marquis", "Tivoli"],
    "LC": ["Castries", "Bisée", "Vieux Fort", "Micoud", "Soufrière", "Dennery", "Gros Islet", "Anse la Raye", "Choiseul", "Laborie"],
    "VC": ["Kingstown", "Georgetown", "Byera", "Chateaubelair", "Barrouallie", "Layou", "Biabou", "Calliaqua", "Port Elizabeth", "Union Island"],
    "AG": ["St. John's", "All Saints", "Liberta", "Potters Village", "Bolans", "Swetes", "Parham", "Falmouth", "Codrington", "Piggotts"],
    "DM": ["Roseau", "Portsmouth", "Marigot", "Berekua", "Mahaut", "Wesley", "Salisbury", "Soufrière", "Grand Bay", "Castle Bruce"],
    "KN": ["Basseterre", "Charlestown", "Sandy Point Town", "Cayon", "Dieppe Bay Town", "Fig Tree", "Newcastle", "Old Road Town", "Tabernacle", "Gingerland"],
    "BR": ["São Paulo", "Rio de Janeiro", "Brasília", "Salvador", "Fortaleza", "Belo Horizonte", "Manaus", "Curitiba", "Recife", "Porto Alegre", "Belém", "Goiânia", "Guarulhos", "Campinas", "São Luís"],
    "AR": ["Buenos Aires", "Córdoba", "Rosario", "Mendoza", "La Plata", "San Miguel de Tucumán", "Mar del Plata", "Salta", "Santa Fe", "San Juan", "Resistencia", "Neuquén"],
    "CL": ["Santiago", "Valparaíso", "Concepción", "La Serena", "Antofagasta", "Temuco", "Rancagua", "Talca", "Arica", "Iquique", "Puerto Montt", "Chillán"],
    "CO": ["Bogotá", "Medellín", "Cali", "Barranquilla", "Cartagena", "Cúcuta", "Bucaramanga", "Pereira", "Santa Marta", "Ibagué", "Manizales", "Villavicencio"],
    "PE": ["Lima", "Arequipa", "Trujillo", "Chiclayo", "Piura", "Iquitos", "Cusco", "Chimbote", "Huancayo", "Tacna"],
    "VE": ["Caracas", "Maracaibo", "Valencia", "Barquisimeto", "Maracay", "Ciudad Guayana", "San Cristóbal", "Maturín", "Barcelona", "Puerto La Cruz"],
    "EC": ["Guayaquil", "Quito", "Cuenca", "Santo Domingo", "Machala", "Durán", "Manta", "Portoviejo", "Loja", "Ambato"],
    "BO": ["Santa Cruz de la Sierra", "La Paz", "El Alto", "Cochabamba", "Sucre", "Oruro", "Tarija", "Potosí", "Sacaba", "Montero"],
    "PY": ["Asunción", "Ciudad del Este", "San Lorenzo", "Luque", "Capiatá", "Lambaré", "Fernando de la Mora", "Limpio", "Ñemby", "Encarnación"],
    "UY": ["Montevideo", "Salto", "Ciudad de la Costa", "Paysandú", "Las Piedras", "Rivera", "Maldonado", "Tacuarembó", "Melo", "Mercedes"],
    "GY": ["Georgetown", "Linden", "New Amsterdam", "Anna Regina", "Bartica", "Skeldon", "Rosignol", "Mahaica", "Corriverton", "Parika"],
    "SR": ["Paramaribo", "Lelydorp", "Nieuw Nickerie", "Moengo", "Nieuw Amsterdam", "Mariënburg", "Wageningen", "Albina", "Groningen", "Brokopondo"],
    "AU": ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Gold Coast", "Newcastle", "Canberra", "Wollongong", "Hobart", "Geelong", "Townsville", "Cairns", "Darwin"],
    "NZ": ["Auckland", "Wellington", "Christchurch", "Hamilton", "Tauranga", "Napier-Hastings", "Dunedin", "Palmerston North", "Nelson", "Rotorua"],
    "FJ": ["Suva", "Nadi", "Lautoka", "Labasa", "Nausori", "Ba", "Sigatoka", "Levuka", "Rakiraki", "Savusavu"],
    "PG": ["Port Moresby", "Lae", "Mount Hagen", "Popondetta", "Madang", "Wewak", "Goroka", "Kokopo", "Kimbe", "Mendi"],
    "SB": ["Honiara", "Auki", "Gizo", "Buala", "Kirakira", "Tulagi", "Lata", "Buin", "Munda", "Taro"],
    "VU": ["Port Vila", "Luganville", "Norsup", "Isangel", "Sola", "Lakatoro", "Saratamata", "Longana", "Lenakel", "Ambae"],
    "WS": ["Apia", "Vaitele", "Faleula", "Siusega", "Malie", "Vailoa", "Lalovaea", "Nofoalii", "Leauva'a", "Fasito'outa"],
    "TO": ["Nuku'alofa", "Neiafu", "Haveluloto", "Vaini", "Pangai", "'Ohonua", "Kolonga", "Tofoa", "Longoteme", "Houma"],
]
